// RobotBuilder Version: 1.5
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc2538.Stronghold2538.subsystems;

import org.usfirst.frc2538.Stronghold2538.*;
import org.usfirst.frc2538.Stronghold2538.commands.*;

import com.ni.vision.NIVision.Range;

import edu.wpi.first.wpilibj.AnalogGyro;
import edu.wpi.first.wpilibj.Joystick;
import edu.wpi.first.wpilibj.RobotDrive;
import edu.wpi.first.wpilibj.SpeedController;
import edu.wpi.first.wpilibj.Ultrasonic;
import edu.wpi.first.wpilibj.command.Subsystem;
import edu.wpi.first.wpilibj.interfaces.Gyro;
import edu.wpi.first.wpilibj.smartdashboard.SmartDashboard;


/**
 *
 */
public class driveSystem extends Subsystem {
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    private final SpeedController leftMotor = RobotMap.driveSystemLeftMotor;
    private final SpeedController rightMotor = RobotMap.driveSystemRightMotor;
    private final RobotDrive robotDrive21 = RobotMap.driveSystemRobotDrive21;
    private final AnalogGyro analogGyro = RobotMap.driveSystemAnalogGyro;
    private final Ultrasonic ultrasonic = RobotMap.driveSystemUltrasonic;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
   public boolean isInverted = false;
   public double JOYSTICK_TOLERANCE = .05;
   public double ultraRange = ultrasonic.getRangeInches();
   public double angle = analogGyro.getAngle();
   public double gyroScaling = .03; 
   public double ultraForwardRange = 48;
   public double turnAngle = 40;
   public double turnSpeed = .25;
   public double goalRange = 1;
  
    // Put methods for controlling this subsystem
    // here. Call these from Commands.

    public void initDefaultCommand() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND

        setDefaultCommand(new arcadeDrive());

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND
	
        // Set the default command for a subsystem here.
        //setDefaultCommand(new MySpecialCommand());
    }
//    static RobotDrive drive;
	public void arcadeDriveSystem(){
		Joystick driveJoystick = Robot.oi.driveStick;
		Joystick secondaryStick = Robot.oi.secondaryStick;
		double yValue = driveJoystick.getY();
		double xValue = driveJoystick.getX();
		double direction = driveJoystick.getDirectionDegrees();
		double throttle = driveJoystick.getZ() * (-.25) + .75;
		SmartDashboard.putDouble("y", yValue);
		SmartDashboard.putDouble("x", xValue);
		//getThrottle is actually getZ on madcats joystick
		robotDrive21.arcadeDrive(backwards(minimumTolerance(yValue)) * throttle, reverseTurn(minimumTolerance(xValue)) * throttle);
		
	}
	private double minimumTolerance(double magnitude) {
    	if (magnitude < JOYSTICK_TOLERANCE && magnitude > -JOYSTICK_TOLERANCE) {
			return 0;
		}
    	else {
    		return magnitude;
		}
    }
	public double backwards(double yValue){
		if(isInverted){
			return - yValue;
		}
		return yValue;
	}
	public double reverseTurn(double xValue){
		if (isInverted) {
			return -xValue;
		}
		return xValue;
	}
	public boolean GyroStraight() {
		if (ultraRange <= ultraForwardRange) {	
			robotDrive21.arcadeDrive(-1.0, -angle * gyroScaling);
			return false;
		}
		else{
			return true;
		}
	}
	public boolean GyroTurn() {
		if (angle < turnAngle) {
			robotDrive21.arcadeDrive(0.0, turnSpeed);
			return false;
		}
		else {
			return true;
		}
	}
	public boolean driveForward() {
		if (ultraRange < goalRange) {
			robotDrive21.arcadeDrive(-1.0, 0);
			return false;
		}
		else {
			return true;
		}
	}
	public void stopDriving() {
		robotDrive21.arcadeDrive(0.0, 0.0);
	}
}
